In [166]:
# Data Handling
import pandas as pd
import numpy as np

#  Visualization
import seaborn as sns
import matplotlib.pyplot as plt

In [167]:
df = pd.read_csv("data/raw/photos.tsv000", sep="\t")
df.shape

(25000, 31)

In [168]:
pd.set_option("display.max_columns", None)

**1- EDA**

In [169]:
df.head(2)

,photo_id,photo_url,photo_image_url,photo_submitted_at,photo_featured,photo_width,photo_height,photo_aspect_ratio,photo_description,photographer_username,photographer_first_name,photographer_last_name,exif_camera_make,exif_camera_model,exif_iso,exif_aperture_value,exif_focal_length,exif_exposure_time,photo_location_name,photo_location_latitude,photo_location_longitude,photo_location_country,photo_location_city,stats_views,stats_downloads,ai_description,ai_primary_landmark_name,ai_primary_landmark_latitude,ai_primary_landmark_longitude,ai_primary_landmark_confidence,blur_hash
0,luPOnViYl7I,https://unsplash.com/photos/luPOnViYl7I,https://images.unsplash.com/photo-141613878277...,2014-11-16 11:48:22.003158,t,3110,2074,1.50,NaN,tanguysauvin,Tanguy,Sauvin,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1894069,11058,black water strider,NaN,NaN,NaN,NaN,LLIFY%Rp0Kxuof?bV@IU01-:%LM{
1,OdAqbedkfiA,https://unsplash.com/photos/OdAqbedkfiA,https://images.unsplash.com/28/tree-sky.jpg,2014-02-17 12:45:34,t,1500,2250,0.67,Conifers at the foot of snowy mountains,sylwiabartyzel,Sylwia,Bartyzel,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,8288693,40344,silhouette of trees and snowy mountains,NaN,NaN,NaN,NaN,L-JI30ofRjRj~qfPayfQRjWBt7t7

In [170]:
df.isnull().sum()

photo_id                              0
photo_url                             0
photo_image_url                       0
photo_submitted_at                    0
photo_featured                        0
photo_width                           0
photo_height                          0
photo_aspect_ratio                    0
photo_description                 13949
photographer_username                 0
photographer_first_name               0
photographer_last_name             1668
exif_camera_make                   2872
exif_camera_model                  2916
exif_iso                           3279
exif_aperture_value                3671
exif_focal_length                  3553
exif_exposure_time                 3304
photo_location_name               14840
photo_location_latitude           17143
photo_location_longitude          17143
photo_location_country            15724
photo_location_city               18536
stats_views                           0
stats_downloads                       0
ai_description                        1
ai_primary_landmark_name          23684
ai_primary_landmark_latitude      23684
ai_primary_landmark_longitude     23684
ai_primary_landmark_confidence    23684
blur_hash                             9
dtype: int64

In [171]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 25000 entries, 0 to 24999
Data columns (total 31 columns):
 #   Column                          Non-Null Count  Dtype
---  ------                          --------------  -----
 0   photo_id                        25000 non-null  object
 1   photo_url                       25000 non-null  object
 2   photo_image_url                 25000 non-null  object
 3   photo_submitted_at              25000 non-null  object
 4   photo_featured                  25000 non-null  object
 5   photo_width                     25000 non-null  int64
 6   photo_height                    25000 non-null  int64
 7   photo_aspect_ratio              25000 non-null  float64
 8   photo_description               11051 non-null  object
 9   photographer_username           25000 non-null  object
 10  photographer_first_name         25000 non-null  object
 11  photographer_last_name          23332 non-null  object
 12  exif_camera_make                22128 non-null  object
 13  exif_camera_model               22084 non-null  object
 14  exif_iso                        21721 non-null  float64
 15  exif_aperture_value             21329 non-null  object
 16  exif_focal_length               21447 non-null  object
 17  exif_exposure_time              21696 non-null  object
 18  photo_location_name             10160 non-null  object
 19  photo_location_latitude         7857 non-null   float64
 20  photo_location_longitude        7857 non-null   float64
 21  photo_location_country          9276 non-null   object
 22  photo_location_city             6464 non-null   object
 23  stats_views                     25000 non-null  int64
 24  stats_downloads                 25000 non-null  int64
 25  ai_description                  24999 non-null  object
 26  ai_primary_landmark_name        1316 non-null   object
 27  ai_primary_landmark_latitude    1316 non-null   float64
 28  ai_primary_landmark_longitude   1316 non-null   float64
 29  ai_primary_landmark_confidence  1316 non-null   float64
 30  blur_hash                       24991 non-null  object
dtypes: float64(7), int64(4), object(20)
memory usage: 5.9+ MB

In [172]:
df["photo_location_country"].value_counts()

photo_location_country
United States     2472
Canada             466
United Kingdom     425
Australia          351
Italy              313
                  ...
Brasov               1
Rhodes               1
Србија               1
Transilvania         1
Panamá               1
Name: count, Length: 443, dtype: int64

In [173]:
df.describe()

,photo_width,photo_height,photo_aspect_ratio,exif_iso,photo_location_latitude,photo_location_longitude,stats_views,stats_downloads,ai_primary_landmark_latitude,ai_primary_landmark_longitude,ai_primary_landmark_confidence
count,25000.000000,25000.000000,25000.000000,21721.000000,7857.000000,7857.000000,2.500000e+04,2.500000e+04,1316.000000,1316.000000,1316.000000
mean,4442.132240,4181.578720,1.151629,562.134846,33.511611,-19.077007,4.426662e+06,2.097857e+04,38.446652,-45.045024,18.678672
std,1354.360837,1385.791633,0.411964,1388.494452,25.597914,79.062258,4.520231e+07,8.350188e+04,21.963833,77.033844,28.393044
min,768.000000,563.000000,0.340000,0.000000,-82.862752,-178.139472,1.386700e+04,1.290000e+02,-51.466841,-159.725761,0.143585
25%,3456.000000,3264.000000,0.670000,100.000000,30.759658,-89.401230,4.427080e+05,2.179000e+03,37.277582,-116.510696,0.459758
50%,4074.000000,4000.000000,1.330000,200.000000,41.204380,-0.311950,8.410950e+05,4.646000e+03,43.216145,-72.545418,0.677706
75%,5472.000000,5184.000000,1.500000,400.000000,48.176667,14.550072,2.281087e+06,1.304200e+04,48.710016,10.136926,41.800691
max,16384.000000,16384.000000,4.130000,51200.000000,79.866667,178.085191,2.732294e+09,4.929347e+06,68.363153,176.087144,97.641426

In [174]:
missing = df.isnull().mean() * 100
missing.sort_values(ascending=False)

ai_primary_landmark_confidence    94.736
ai_primary_landmark_longitude     94.736
ai_primary_landmark_latitude      94.736
ai_primary_landmark_name          94.736
photo_location_city               74.144
photo_location_latitude           68.572
photo_location_longitude          68.572
photo_location_country            62.896
photo_location_name               59.360
photo_description                 55.796
exif_aperture_value               14.684
exif_focal_length                 14.212
exif_exposure_time                13.216
exif_iso                          13.116
exif_camera_model                 11.664
exif_camera_make                  11.488
photographer_last_name             6.672
blur_hash                          0.036
ai_description                     0.004
photo_url                          0.000
photographer_first_name            0.000
photographer_username              0.000
photo_aspect_ratio                 0.000
photo_height                       0.000
stats_views                        0.000
stats_downloads                    0.000
photo_width                        0.000
photo_featured                     0.000
photo_submitted_at                 0.000
photo_image_url                    0.000
photo_id                           0.000
dtype: float64

In [175]:
for col in ["exif_camera_make", "exif_iso", "exif_aperture_value", "exif_focal_length", "exif_exposure_time"]:
    print(df[col].value_counts().head(10))
    print()

exif_camera_make
Canon                          8433
NIKON CORPORATION              4548
SONY                           3861
FUJIFILM                       1483
DJI                             920
Apple                           624
Panasonic                       456
Hasselblad                      278
RICOH IMAGING COMPANY, LTD.     194
OLYMPUS CORPORATION             166
Name: count, dtype: int64

exif_iso
100.0     7286
200.0     2713
400.0     1959
800.0     1186
250.0      789
320.0      774
160.0      721
500.0      642
640.0      640
1600.0     606
Name: count, dtype: int64

exif_aperture_value
2.8    2933
5.6    1931
1.8    1703
4.0    1690
1.4    1085
2.2    1038
8.0     985
3.5     827
4.5     802
6.3     735
Name: count, dtype: int64

exif_focal_length
50.0     3037
35.0     1918
24.0     1197
18.0      836
70.0      712
55.0      700
85.0      672
16.0      538
200.0     500
4.7       489
Name: count, dtype: int64

exif_exposure_time
1/250     1343
1/200     1258
1/500     1250
1/125     1220
1/160     1101
1/320     1070
1/400     1056
1/100     1022
1/1000     893
1/800      882
Name: count, dtype: int64

**Keeping the columns that are useful for our need**

In [176]:
keepcol = [
    "photo_id", "photo_url", "photo_image_url", "photo_submitted_at", "photo_featured",
    "photo_width", "photo_height", "photo_aspect_ratio",
    "photographer_username", "exif_camera_make", "exif_camera_model", "exif_iso",
    "exif_aperture_value", "exif_focal_length", "exif_exposure_time",
    "photo_location_country", "stats_views", "stats_downloads", "ai_description"
]

In [177]:
clean_data = df[keepcol].copy()

In [178]:
clean_data.head(1)

,photo_id,photo_url,photo_image_url,photo_submitted_at,photo_featured,photo_width,photo_height,photo_aspect_ratio,photographer_username,exif_camera_make,exif_camera_model,exif_iso,exif_aperture_value,exif_focal_length,exif_exposure_time,photo_location_country,stats_views,stats_downloads,ai_description
0,luPOnViYl7I,https://unsplash.com/photos/luPOnViYl7I,https://images.unsplash.com/photo-141613878277...,2014-11-16 11:48:22.003158,t,3110,2074,1.5,tanguysauvin,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1894069,11058,black water strider

In [179]:
clean_data.shape

(25000, 19)

**2- Data Cleaning**

In [180]:
clean_data.duplicated(subset="photo_id").sum()

0

In [181]:
clean_data = clean_data.rename(columns={
    "photo_submitted_at": "submitted_at",
    "photo_featured": "featured",
    "photo_width": "width",
    "photo_height": "height",
    "photo_aspect_ratio": "aspect_ratio",
    "photographer_username": "photographer",
    "exif_camera_make": "camera_make",
    "exif_camera_model": "camera_model",
    "exif_iso": "iso",
    "exif_aperture_value": "aperture",
    "exif_focal_length": "focal_length",
    "exif_exposure_time": "shutter",
    "photo_location_country": "country",
    "stats_views": "views",
    "stats_downloads": "downloads",
})
clean_data.columns

Index(['photo_id', 'photo_url', 'photo_image_url', 'submitted_at', 'featured',
       'width', 'height', 'aspect_ratio', 'photographer', 'camera_make',
       'camera_model', 'iso', 'aperture', 'focal_length', 'shutter', 'country',
       'views', 'downloads', 'ai_description'],
      dtype='object')

In [182]:
clean_data["has_exif"] = clean_data["camera_make"].notna()
clean_data["has_exif"].value_counts()

has_exif
True     22128
False     2872
Name: count, dtype: int64

In [183]:
for col in ["aperture", "focal_length"]:
    numbers = pd.to_numeric(clean_data[col], errors="coerce")
    bad = numbers.isna() & clean_data[col].notna()
    print(col, bad.sum())
    print(clean_data.loc[bad, col].value_counts().head())
    print()

aperture 25
aperture
undef    10
5,6       3
7,5       2
f/5       2
f4.0      1
Name: count, dtype: int64

focal_length 35
focal_length
50mm     5
35mm     4
85mm     3
50 mm    2
14mm     2
Name: count, dtype: int64

In [184]:
clean_data["brand"] = clean_data["camera_make"].str.lower().str.split().str[0]
clean_data["brand"].value_counts().head(20)

brand
canon         8436
nikon         4739
sony          3991
fujifilm      1519
dji            930
apple          624
panasonic      456
olympus        328
hasselblad     279
ricoh          199
samsung        112
leica           91
pentax          60
gopro           55
google          41
noritsu         37
fuji            35
huawei          33
xiaomi          21
zwo             15
Name: count, dtype: int64

In [185]:
clean_data.head()

,photo_id,photo_url,photo_image_url,submitted_at,featured,width,height,aspect_ratio,photographer,camera_make,camera_model,iso,aperture,focal_length,shutter,country,views,downloads,ai_description,has_exif,brand
0,luPOnViYl7I,https://unsplash.com/photos/luPOnViYl7I,https://images.unsplash.com/photo-141613878277...,2014-11-16 11:48:22.003158,t,3110,2074,1.50,tanguysauvin,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1894069,11058,black water strider,False,NaN
1,OdAqbedkfiA,https://unsplash.com/photos/OdAqbedkfiA,https://images.unsplash.com/28/tree-sky.jpg,2014-02-17 12:45:34,t,1500,2250,0.67,sylwiabartyzel,NaN,NaN,NaN,NaN,NaN,NaN,NaN,8288693,40344,silhouette of trees and snowy mountains,False,NaN
2,w9UQ02x-QsU,https://unsplash.com/photos/w9UQ02x-QsU,https://images.unsplash.com/photo-141883330961...,2014-12-17 16:23:53.442485,t,3264,4896,0.67,jenellehayes,FUJIFILM,X-E1,200.0,7.1,37.4,1/350,NaN,2832184,26732,landscape photography of body of water near mo...,True,fujifilm
3,491PQ04olSg,https://unsplash.com/photos/491PQ04olSg,https://images.unsplash.com/photo-141389725556...,2014-10-21 13:16:22.143136,t,3901,2602,1.50,radel,NIKON CORPORATION,NIKON 1 V1,100.0,4.0,11.4,1/125,Italy,10035571,60182,landscape of house near electric post,True,nikon
4,_rZrkLPKPcU,https://unsplash.com/photos/_rZrkLPKPcU,https://images.unsplash.com/photo-143490956140...,2015-06-21 17:59:49.619717,t,5616,3744,1.50,anthonydelanoix,Canon,Canon EOS 5D Mark II,250.0,4.0,24.0,1/320,NaN,2609764,22351,bear on body of water,True,canon

In [186]:
# fix aperture format
clean_data["aperture"] = clean_data["aperture"].astype(str).str.replace(",", ".").str.replace("f/", "").str.replace("f", "")
clean_data["aperture"] = pd.to_numeric(clean_data["aperture"], errors="coerce")

In [187]:
# fix focal_length format
clean_data["focal_length"] = clean_data["focal_length"].astype(str).str.replace("mm", "").str.strip()
clean_data["focal_length"] = pd.to_numeric(clean_data["focal_length"], errors="coerce")

In [188]:
# making shutter speed to seconds
def to_seconds(x):
    try:
        if "/" in str(x):
            a, b = str(x).split("/")
            return float(a) / float(b)
        return float(x)
    except:
        return None

clean_data["shutter"] = clean_data["shutter"].apply(to_seconds)

In [189]:
# we can't have iso = 0
clean_data.loc[clean_data["iso"] == 0, "iso"] = np.nan

In [190]:
# impossible aperture values
clean_data.loc[(clean_data["aperture"] < 0.95) | (clean_data["aperture"] > 32), "aperture"] = np.nan

In [191]:
# a lens can't have 0mm focal length
clean_data.loc[clean_data["focal_length"] == 0, "focal_length"] = np.nan

In [192]:
# fixing date formating, and featured to be true or false 
clean_data["submitted_at"] = pd.to_datetime(clean_data["submitted_at"], format="mixed")
clean_data["featured"] = clean_data["featured"] == "t"

In [193]:
# some brands have the same name but different writing styles
clean_data["brand"] = clean_data["brand"].replace("fuji", "fujifilm")
# filling na values with unknown
clean_data["brand"] = clean_data["brand"].fillna("unknown")

In [194]:
phones = ["apple", "samsung", "google", "huawei", "xiaomi"]

def get_type(brand):
    if brand == "unknown":
        return "unknown"
    elif brand in phones:
        return "phone"
    elif brand == "dji":
        return "drone"
    else:
        return "camera"

clean_data["camera_type"] = clean_data["brand"].apply(get_type)

# DJI drones with Hasselblad cameras
is_drone = clean_data["camera_model"].str.contains("L1D|L2D", na=False)
clean_data.loc[is_drone, "camera_type"] = "drone"

clean_data["camera_type"].value_counts()

camera_type
camera     20104
unknown     2872
drone       1193
phone        831
Name: count, dtype: int64

In [195]:
# creating a new col "orientation" depending is the image landscape or portrait or square
def get_orientation(ratio):
    if ratio > 1.05:
        return "landscape"
    elif ratio < 0.95:
        return "portrait"
    else:
        return "square"

clean_data["orientation"] = clean_data["aspect_ratio"].apply(get_orientation)
clean_data["year"] = clean_data["submitted_at"].dt.year
clean_data["download_rate"] = clean_data["downloads"] / clean_data["views"]
clean_data["megapixels"] = clean_data["width"] * clean_data["height"] / 1_000_000

In [196]:
# filling the country nulls
clean_data["country"] = clean_data["country"].fillna("Unknown")

In [197]:
clean_data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 25000 entries, 0 to 24999
Data columns (total 26 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   photo_id         25000 non-null  object
 1   photo_url        25000 non-null  object
 2   photo_image_url  25000 non-null  object
 3   submitted_at     25000 non-null  datetime64[ns]
 4   featured         25000 non-null  bool
 5   width            25000 non-null  int64
 6   height           25000 non-null  int64
 7   aspect_ratio     25000 non-null  float64
 8   photographer     25000 non-null  object
 9   camera_make      22128 non-null  object
 10  camera_model     22084 non-null  object
 11  iso              21704 non-null  float64
 12  aperture         21295 non-null  float64
 13  focal_length     21372 non-null  float64
 14  shutter          21672 non-null  float64
 15  country          25000 non-null  object
 16  views            25000 non-null  int64
 17  downloads        25000 non-null  int64
 18  ai_description   24999 non-null  object
 19  has_exif         25000 non-null  bool
 20  brand            25000 non-null  object
 21  camera_type      25000 non-null  object
 22  orientation      25000 non-null  object
 23  year             25000 non-null  int32
 24  download_rate    25000 non-null  float64
 25  megapixels       25000 non-null  float64
dtypes: bool(2), datetime64[ns](1), float64(7), int32(1), int64(4), object(11)
memory usage: 4.5+ MB

In [198]:
clean_data.head()

,photo_id,photo_url,photo_image_url,submitted_at,featured,width,height,aspect_ratio,photographer,camera_make,camera_model,iso,aperture,focal_length,shutter,country,views,downloads,ai_description,has_exif,brand,camera_type,orientation,year,download_rate,megapixels
0,luPOnViYl7I,https://unsplash.com/photos/luPOnViYl7I,https://images.unsplash.com/photo-141613878277...,2014-11-16 11:48:22.003158,True,3110,2074,1.50,tanguysauvin,NaN,NaN,NaN,NaN,NaN,NaN,Unknown,1894069,11058,black water strider,False,unknown,unknown,landscape,2014,0.005838,6.450140
1,OdAqbedkfiA,https://unsplash.com/photos/OdAqbedkfiA,https://images.unsplash.com/28/tree-sky.jpg,2014-02-17 12:45:34.000000,True,1500,2250,0.67,sylwiabartyzel,NaN,NaN,NaN,NaN,NaN,NaN,Unknown,8288693,40344,silhouette of trees and snowy mountains,False,unknown,unknown,portrait,2014,0.004867,3.375000
2,w9UQ02x-QsU,https://unsplash.com/photos/w9UQ02x-QsU,https://images.unsplash.com/photo-141883330961...,2014-12-17 16:23:53.442485,True,3264,4896,0.67,jenellehayes,FUJIFILM,X-E1,200.0,7.1,37.4,0.002857,Unknown,2832184,26732,landscape photography of body of water near mo...,True,fujifilm,camera,portrait,2014,0.009439,15.980544
3,491PQ04olSg,https://unsplash.com/photos/491PQ04olSg,https://images.unsplash.com/photo-141389725556...,2014-10-21 13:16:22.143136,True,3901,2602,1.50,radel,NIKON CORPORATION,NIKON 1 V1,100.0,4.0,11.4,0.008000,Italy,10035571,60182,landscape of house near electric post,True,nikon,camera,landscape,2014,0.005997,10.150402
4,_rZrkLPKPcU,https://unsplash.com/photos/_rZrkLPKPcU,https://images.unsplash.com/photo-143490956140...,2015-06-21 17:59:49.619717,True,5616,3744,1.50,anthonydelanoix,Canon,Canon EOS 5D Mark II,250.0,4.0,24.0,0.003125,Unknown,2609764,22351,bear on body of water,True,canon,camera,landscape,2015,0.008564,21.026304

**Note for me:**
- "5,6" is how some European cameras write 5.6, so I swap the comma for a dot.
- errors="coerce" turns anything still broken (like "undef") into missing instead of crashing.
- 1/250 means the shutter was open for 1/250 of a second = 0.004 seconds.
- Some DJI drones use Hasselblad cameras, so I check the model name (L1D, L2D) to label them as drones.
- download_rate = downloads / views, how convincing a photo is, not just how many people saw it.

In [199]:
clean_data[["iso", "aperture", "focal_length", "shutter", "megapixels", "download_rate"]].describe()

,iso,aperture,focal_length,shutter,megapixels,download_rate
count,21704.000000,21295.000000,21372.000000,21672.000000,25000.000000,25000.000000
mean,562.575147,4.923949,67.044898,4.290962,18.972245,0.006912
std,1388.948981,3.715791,94.518967,111.469293,9.645742,0.008919
min,16.000000,0.950000,0.200000,0.000025,0.563000,0.000071
25%,100.000000,2.400000,23.000000,0.001250,12.192768,0.003816
50%,200.000000,4.000000,40.000000,0.004000,17.964296,0.005805
75%,400.000000,6.300000,70.000000,0.010000,24.000000,0.008277
max,51200.000000,32.000000,2032.000000,10800.000000,193.960959,0.851457

In [200]:
clean_data.describe()

,submitted_at,width,height,aspect_ratio,iso,aperture,focal_length,shutter,views,downloads,year,download_rate,megapixels
count,25000,25000.000000,25000.000000,25000.000000,21704.000000,21295.000000,21372.000000,21672.000000,2.500000e+04,2.500000e+04,25000.000000,25000.000000,25000.000000
mean,2018-12-09 18:16:10.411324928,4442.132240,4181.578720,1.151629,562.575147,4.923949,67.044898,4.290962,4.426662e+06,2.097857e+04,2018.468480,0.006912,18.972245
min,2013-06-09 13:57:48,768.000000,563.000000,0.340000,16.000000,0.950000,0.200000,0.000025,1.386700e+04,1.290000e+02,2013.000000,0.000071,0.563000
25%,2018-06-27 07:45:22.916183808,3456.000000,3264.000000,0.670000,100.000000,2.400000,23.000000,0.001250,4.427080e+05,2.179000e+03,2018.000000,0.003816,12.192768
50%,2019-04-27 14:25:56.688719104,4074.000000,4000.000000,1.330000,200.000000,4.000000,40.000000,0.004000,8.410950e+05,4.646000e+03,2019.000000,0.005805,17.964296
75%,2019-12-11 20:28:42.278301696,5472.000000,5184.000000,1.500000,400.000000,6.300000,70.000000,0.010000,2.281087e+06,1.304200e+04,2019.000000,0.008277,24.000000
max,2025-05-25 14:36:28.554051,16384.000000,16384.000000,4.130000,51200.000000,32.000000,2032.000000,10800.000000,2.732294e+09,4.929347e+06,2025.000000,0.851457,193.960959
std,NaN,1354.360837,1385.791633,0.411964,1388.948981,3.715791,94.518967,111.469293,4.520231e+07,8.350188e+04,1.724809,0.008919,9.645742

In [201]:
clean_data.to_csv("data/clean_data.csv", index=False)
clean_data.shape

(25000, 26)